### ISSUE TITLE
感谢老铁的代码支援，居然没有星，简直没天理

### ISSUE THREAD

**Issue by moker-monkey** [alekoshen712/vue-clickOutside#1]
虽然是什么逻辑还没看懂，但已经用上了，我还是得自我提高啊，以后好封装多一些工具提高效率

**Comment by alekoshen712** [comment]
感谢star..抱歉事隔2年才看到=,= 
其实也只是把饿了么的代码抽离了一下哈..主要的逻辑还是参考element-ui的
现在的你肯定能看懂啦
